### ISSUE TITLE
required packages

### ISSUE THREAD

**Issue by Nawarix** [anetrusov/ZabbixDBA#11]
Do I have to install any Oracle Packages  like instant client 
I managed to start zdba service and I checked the log file the service is started and a thread for my db connectiong is started but zabbix server didn't receive any traps.
I tried to change the level of logging but nothing new added to the log file, any suggestions

Thank you

**Comment by Nawarix** [comment]
I don't know if this project still alive
anyway I managed to run the module I found out I have to install DBD::Oracle using cpanm,then install perl-DBI, and install oracle-instantclient.  it's collecting data from db i got the message from log file "completed fetching data on 'XXXDB', elapsed: 0.648831"

but zabbix_server didn't receive the data and I got from zabbix_server.log the message " Message from xxx.xxx.xxx.xxx is longer than expected 36 bytes. Message ignored"

I'm running zabbix 3.0.2 is it compatible issue ??

**Comment by netrusov** [comment]
@Nawarix 

omg, sorry for delay, I didn't see that this issue was opened (was little busy with new project). yes, it's still alive.

I've tested zdba with Zabbix 3.x and it worked fine (even LLD). I guess that issue is on Zabbix side.

I've tried to find if they changed something in new releases, but documentation for zabbix_sender protocol didn't change since v1.8 (https://www.zabbix.com/documentation/1.8/protocols)

I'll try to install newest version of Zabbix and check again.

Thanks.

P.S.: the README indicated that you should install appropriate DBD module

**Comment by netrusov** [comment]
@Nawarix 

yep, I have latest Zabbix Appliance 3.0.2 running under VM for testing purposes. works like a charm.
here's my configuration (used mysql database, but it's not important)

```
{
    zabbix => {
        server  => 'localhost',
        port    => 10051,
        timeout => 30,
    },
    daemon => {
        sleep => 120,
    },
    db => {
        default => {
            user        => 'zabbix',
            password    => '***',
            query_list  => 'query.props.pl',
            sleep       => 30,
            retry_count => 1,
        },
        list   => ['zabbix'],
        zabbix => {
            dsn        => 'DBI:mysql:zabbix',
            query_list => 'mysql.query.props.pl',
            sleep      => 15,
        },
    }
}
```

query list (yeah, pretty complex)

```
{
    query_list => ['test'],
    test       => {
        query => 'select 1'
    }
}
```

and screenshot from Zabbix web interface

![image](https://cloud.githubusercontent.com/assets/6795441/15792339/546e8ae8-29e5-11e6-8953-d522dd2e6cd7.png)

**Comment by Nawarix** [comment]
Hi
Thank you for your help, I managed to collect only the alive trap I had an error in the configuration file, I named the connection with the oracle service name instead of the host name.

but I still not getting the other data.
the thing is I installed the zdba service on the zabbix server to collect the Oracle DB which is installed on another server, I don't know if this need extra configurations.

**Comment by netrusov** [comment]
@Nawarix 

good day,

name of service does not affect on connection, it's only used to identify name of host in Zabbix. connection string itself is stored in "dsn" parameter.

for better understanding, this is what generated for "alive"

```
{
  "host": "my_host_in_zabbix",
  "key": "alive",
  "value": "1"
}
```

did you configure query list properly? I suggest you to check each configuration file by issuing "perl -c ${FILENAME}". it will compile perl structures and show errors that were find, but will not run code.
for example:

```
perl -c /opt/zdba/conf/config.pl
```

this way you will be sure that you didn't break something when changes were made to configuration

**Comment by netrusov** [comment]
@Nawarix 

Hello,

Think I've fixed the issue. Please try with the newest version (if you still interested).
Closing this case.

Thanks,
Alex.
