### ISSUE TITLE
Отсутствуют данные в Zabbix

### ISSUE THREAD

**Issue by ghost** [anetrusov/ZabbixDBA#13]
Приветствую.
Настроил скрипт как написано.
Сервис успешно запустился, в логах ZabbixDBA.log ошибок нет.
Но Zabbix данные не получают.

![image](https://cloud.githubusercontent.com/assets/12830151/17250650/f7988d92-55ad-11e6-8b7b-8d02a1bfe4d3.png)

Версия заббикса и агента - 3.0.2

cpanm DBD::Oracle
DBD::Oracle is up to date. (1.74)

Подскажите, пожалуйста, почему данные не отправляются в заббикс?

**Comment by pbobrovnikov** [comment]
При ручном запуске:
perl /opt/zdba/ZabbixDBA.pl /opt/zdba/config.pl

Can't use an undefined value as a HASH reference at /opt/zdba/ZabbixDBA.pl line 57.

**Comment by ghost** [comment]
При ручном запуске:

root@host:/opt/zdba# perl /opt/zdba/ZabbixDBA.pl /opt/zdba/conf/config.pl

...и висит

**Comment by netrusov** [comment]
@pbobrovnikov 

Добрый день!

А в логе есть сообщения о том, что ZabbixDBA подключился к БД и делает выборки?

Например, вот так:

```
[%s:%d] connected to '%s@%s' (%s)
[%s:%d] completed fetching data on '%s', elapsed: %s
```

В данный момент я занимаюсь рефакторингом кода и ввожу более детальную систему логирования, чтобы не возникало проблем с дебагом.

**Comment by ghost** [comment]
Таких сообщений нет.
Есть такие:
Zdba.log
[2016/08/01 11:05:47][INFO ] [main:68] starting thread for DEV
[2016/08/01 11:05:50][INFO ] [main:68] starting thread for DEV
[2016/08/01 11:05:53][INFO ] [main:68] starting thread for DEV
[2016/08/01 11:05:56][INFO ] [main:68] starting thread for DEV
[2016/08/01 11:05:59][INFO ] [main:68] starting thread for DEV

zdba.err
Thread 6 terminated abnormally: install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntshcore.so.12.1: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190.
 at (eval 161) line 3 thread 6.
Compilation failed in require at (eval 161) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /opt/zdba/lib/ZDBA/Controller.pm line 48 thread 6.

**Comment by ghost** [comment]
но файл такой существует:
root@host:/opt/zdba/log# ll /usr/lib64/perl5/DynaLoader.pm
-rwxrwxrwx. 1 root root 24941 Sep 12  2015 /usr/lib64/perl5/DynaLoader.pm*

**Comment by netrusov** [comment]
@pbobrovnikov 

Это уже кое-что. А драйвера с официального сайта Oracle были установлены? Если были и ZDBA их не видит (были установлены в кастомную директорию), то нужно прописать переменные окружения `ORACLE_HOME` и `LD_LIBRARY_PATH` в файле `init.d/zdba`. Можно и в `.bashrc` при условии, что демон запускается вручную и из-под определенного пользователя, но я бы рекомендовал либо установить эти переменные глобально, либо только для демона.

**Comment by netrusov** [comment]
@pbobrovnikov 

Только не найден файл `libclntshcore.so.12.1`, который должен идти вместе с драйверами. Как я уже сказал, ошибка может скрываться в `LD_LIBRARY_PATH` - там обязательно должна быть указана директория с библиотеками Oracle

**Comment by ghost** [comment]
Что я сделал:
1) добавил в init.d/zdba строки:
ORACLE_SID=DEV
ORACLE_HOME=/oracle/DEV/121
LD_LIBRARY_PATH=/usr/sap/DEV/SYS/exe/run:/usr/sap/DEV/SYS/exe/uc/linuxx86_64:/oracle/client/12x/instantclient

2) root@sap-test:/opt/zdba/log# env | grep LD
LD_LIBRARY_PATH=/usr/sap/DEV/SYS/exe/run:/usr/sap/DEV/SYS/exe/uc/linuxx86_64:/oracle/client/12x/instantclient
root@sap-test:/opt/zdba/log# env | grep ORACLE
ORACLE_SID=DEV
ORACLE_HOME=/oracle/DEV/121

3) root@host:/opt/zdba/log# echo $ORACLE_HOME/lib >> /etc/ld.so.conf
root@host:/opt/zdba/log# ldconfig

Ошибки из zdba.err ушли, но теперь другая ошибка:
[2016/08/01 11:36:02][INFO ] [main:68] starting thread for DEV
[2016/08/01 11:36:02][ERROR] [ZDBA::Controller:53] connection failed for 'zabbix@DEV' : ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var  or PATH (Windows) and or NLS settings, permissions, etc.

**Comment by netrusov** [comment]
@pbobrovnikov 

Странная ошибка. Во-первых, совпадают ли версии библиотек в `/oracle/DEV/121` и `/oracle/client/12x/instantclient`? Я бы все же рекомендовал для демона указать, что `/oracle/client/12x/instantclient` и есть `ORACLE_HOME` (я всегда так и делаю, т.к. ставлю ZDBA на машину, где не установлена СУБД). Также проверить права пользователя для этих директорий.

**Comment by ghost** [comment]
Версии совпадают.
В скрипте /etc/init.d/zdba я прописал пути:
ORACLE_SID=DEV
ORACLE_HOME=/oracle/DEV/121
LD_LIBRARY_PATH=/usr/sap/DEV/SYS/exe/run:/usr/sap/DEV/SYS/exe/uc/linuxx86_64:/oracle/client/12x/instantclient:/oracle/DEV/121/lib
NLS_LANG=AMERICAN_AMERICA.UTF8

Права на каталоги у root (так как от него идет запуск /etc/init.d/zdba) есть. Где еще может быть косяк?

**Comment by netrusov** [comment]
@pbobrovnikov 

[Здесь](https://community.oracle.com/thread/874112), например, указывают на то, что установлена переменная `ORACLE_SID`.
Как мне кажется, стоит ее убрать, написав в том же `init.d/zdba` команду `unset ORACLE_SID`.

Также там упоминается, что причиной могло послужить одновременное использование `instant client` и бинарников СУБД. Вполне возможно, что при компиляции `DBD::Oracle` что-то пошло не так. Какие библиотеки были подключены при компиляции этого модуля?

**Comment by ghost** [comment]
Если остановить службу и запустить руками:
perl /opt/zdba/ZabbixDBA.pl /opt/zdba/conf/config.pl

[2016/08/01 12:31:30][ERROR] [ZDBA::Configurator:32] Failure compiling '/opt/zdba/conf/extra.query.props.pl':  at /opt/zdba/lib/Configurator.pm line 32 thread 1.
        Configurator::load('ZDBA::Configurator=HASH(0x1d1daa8)') called at /opt/zdba/lib/ZDBA/Configurator.pm line 29 thread 1
        ZDBA::Configurator::**ANON**() called at /usr/local/share/perl5/Try/Tiny.pm line 92 thread 1
        eval {...} called at /usr/local/share/perl5/Try/Tiny.pm line 83 thread 1
        Try::Tiny::try('CODE(0x2cac980)', 'Try::Tiny::Catch=REF(0x2c97f28)') called at /opt/zdba/lib/ZDBA/Configurator.pm line 34 thread 1
        ZDBA::Configurator::**ANON**('CODE(0x2740c40)', 'ZDBA::Configurator=HASH(0x1d1daa8)') called at (eval 50) line 1 thread 1
        ZDBA::Configurator::**ANON**('ZDBA::Configurator=HASH(0x1d1daa8)') called at (eval 52) line 2 thread 1
        ZDBA::Configurator::load('ZDBA::Configurator=HASH(0x1d1daa8)') called at /opt/zdba/lib/Configurator.pm line 24 thread 1
        Configurator::BUILD('ZDBA::Configurator=HASH(0x1d1daa8)', 'HASH(0x2c60da8)') called at (eval 43) line 64 thread 1
        ZDBA::Configurator::new('ZDBA::Configurator', 'file', '/opt/zdba/conf/extra.query.props.pl') called at /opt/zdba/lib/ZDBA/Configurator.pm line 16 thread 1
        ZDBA::Configurator::**ANON**() called at /usr/local/share/perl5/Try/Tiny.pm line 92 thread 1
        eval {...} called at /usr/local/share/perl5/Try/Tiny.pm line 83 thread 1
        Try::Tiny::try('CODE(0x2cca660)', 'Try::Tiny::Catch=REF(0x2c97dd8)') called at /opt/zdba/lib/ZDBA/Configurator.pm line 20 thread 1
        ZDBA::Configurator::**ANON**('CODE(0x290d048)', 'ZDBA::Configurator', 'file', '/opt/zdba/conf/extra.query.props.pl') called at (eval 46) line 1 thread 1
        ZDBA::Configurator::**ANON**('ZDBA::Configurator', 'file', '/opt/zdba/conf/extra.query.props.pl') called at (eval 48) line 2 thread 1
        ZDBA::Configurator::new('ZDBA::Configurator', 'file', '/opt/zdba/conf/extra.query.props.pl') called at /opt/zdba/lib/ZDBA.pm line 72 thread 1
        ZDBA::monitor('ZDBA=HASH(0x2b978b0)', 'DEV') called at /opt/zdba/ZabbixDBA.pl line 70 thread 1
        main::**ANON**() called at /usr/local/lib64/perl5/forks.pm line 799 thread 1
        eval {...} called at /usr/local/lib64/perl5/forks.pm line 799 thread 1
        threads::new('threads', 'CODE(0x2bac868)') called at /opt/zdba/ZabbixDBA.pl line 70 thread 1

**Comment by netrusov** [comment]
@pbobrovnikov 

Это уже опечатка в конфиге. Можно конфиги проверять командой `perl -c /path/to/config.pl`. Perl скомпилирует файл и покажет ошибки, если они есть.

**Comment by ghost** [comment]
Ошибка: OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var or PATH (Windows) and or NLS settings, permissions, etc. - ушла. bash_profile и иуказание в ENV решили проблему.

Теперь при запуске службы, в логах ошибки как выше, где Вы сказали, что опечатка.
Валидация - ОК

root@host:/opt/zdba/log# perl -c /opt/zdba/conf/config.pl
/opt/zdba/conf/config.pl syntax OK

**Comment by ghost** [comment]
root@host:/opt/zdba# find . -name extra.query.props.pl
такого файла вообще нет))

**Comment by ghost** [comment]
и у Вас в архиве нет.

**Comment by netrusov** [comment]
В конфиге для примера он вставлен. Нужно удалить параметр `extra_query_list`, если не используется.

**Comment by ghost** [comment]
Спасибо! Убрал.
В логах теперь только это:
[2016/08/01 13:06:37][INFO ] [ZDBA:169] completed fetching data on 'DEV', elapsed: 0.373298
[2016/08/01 13:06:39][INFO ] [ZDBA:169] completed fetching data on 'DEV', elapsed: 0.321059
[2016/08/01 13:06:41][INFO ] [ZDBA:169] completed fetching data on 'DEV', elapsed: 0.318011

Но данных нет пока в заббиксе. Нужно вызвать какое-то время?

**Comment by netrusov** [comment]
@pbobrovnikov 

Обычно данные сразу появляются в Zabbix. В Zabbix ведь заведен хост под названием `DEV`?

**Comment by ghost** [comment]
На нашел информации об этом в документации у Вас.
Поменял в конфиге имя хоста на то, которое заведено в Zabbix - данные пошли. Спасибо за помощь! Мониторинг Ваш ВЕЩЬ!

**Comment by netrusov** [comment]
@pbobrovnikov 

Спасибо за положительный отзыв!

Документацию стараюсь обновлять, когда вижу, что люди чего-то не понимают. Все-таки мало фидбека получаю.

Приложение будет постоянно обновляться и улучшаться, так что следите за новостями (:
