### ISSUE TITLE
Tablespace doesn't show values

### ISSUE THREAD

**Issue by mantonik** [anetrusov/ZabbixDBA#24]
Hi

I install zabbixDBA on new installation of Zabbix 3.2 on Linux centos7

When is start process I get error about missing ZDBA.pm
I resolve it by adding 

`use lib '/usr/local/zabbix/zdba/lib';`

to zdba.pl

Process connect to DB and collect data. All query with single response have value.
Tablespace which are discovered are listed but no values.

When I run query manualy as user, query return values.

Example:
SQL> select ta.tablespace_name as ts, ta.used_space \* tb.block_size as bytes
            from dba_tablespace_usage_metrics ta
            join dba_tablespaces tb on ta.tablespace_name = tb.tablespace_name  2    3  ;

TS                                  BYTES

---

SYSAUX                           82247680
SYSTEM                          270139392
TEMP                                    0
UNDOTBS1                          1310720
USERS                             1048576

Thank you for help to understand how this should work.

**Comment by netrusov** [comment]
@mantonik 

Good day,

First of all, issue with libraries already resolved (checkout to the newest version and see `zdba.pl:13`)
I think issue is with Zabbix templates. Unfortunately I didn't fix them yet :(

I've updated template just now. Please download and import it to Zabbix.

Hope this will resolve issue.

**Comment by mantonik** [comment]
Hi
Thank you for the update. 
Template help to resolve missing data for a tablespace.

I tried to use recent code, and I get into problem with bin directory. 
I still have to use 
`use lib '/usr/local/zabbix/zdba/lib';`

In my first version, I already had 

```
use lib File::Spec->catpath( $Bin, 'lib' );
  use ZDBA
```

which should point to correct library
but then I get the problem with log4perl, and I needed add 👍 

```
#Log::Log4perl::init( File::Spec->catpath( $Bin, 'conf', 'log4perl.conf' ) );
Log::Log4perl->init( '/usr/local/zabbix/zdba/conf/log4perl.conf'  );
Log::Any::Adapter->set('Log4perl');
```

then I get into problem of 

```
[root@support log]$ cat zdba.err
Can't open log/zdba.log (No such file or directory) at /usr/local/share/perl5/Log/Log4perl/Appender/File.pm line 124.
```

Base on this chain of problems I believe $Bin is not set correctly which is causing it. 
I will try work on it tomorrow and see if I can find why I have a problem. 

Mariusz

**Comment by netrusov** [comment]
@mantonik 

Hmm, very strange problem. I suggest you run this one-liner to see if there's an issue with defining current directory: `perl -MFindBin='$Bin' -e 'print $Bin, $/'`

Thanks,
Alex.

**Comment by netrusov** [comment]
@mantonik 

No matter... I've found a problem. Need to use `catfile` instead of `catpath`.
Look's like I didn't see it because of `PERL5LIB` environment variable was set to library directory. Will fix in a few minutes.

Thanks for feedback!

**Comment by mantonik** [comment]
Great, Thank you :)

About tablespaces 

Right now I have three entry for each tablespace like 
index
index (%)
index (bytes) 

but only one of them has a value 
index(%)

**Comment by netrusov** [comment]
@mantonik 

Well, if you have latest version of query file with the following section under `discovery`, everything should be fine:

```
      ts_usage_pct => {
        query => q{
            select tablespace_name ts, round(used_percent, 5) pct
            from dba_tablespace_usage_metrics
        },
        keys => { TS => 'PCT' }
      },
      ts_usage_bytes => {
        query => q{
            select ta.tablespace_name as ts, ta.used_space * tb.block_size as bytes
            from dba_tablespace_usage_metrics ta
            join dba_tablespaces tb on ta.tablespace_name = tb.tablespace_name
        },
        keys => { TS => 'BYTES' }
      },
```

You can enable debug log mode and see if ZDBA sends values for `ts_usage_bytes`.

Also, you need to delete item prototype from template which has key `ts_usage` (first one, without mention of measure unit) because I've removed it from template.

**Comment by netrusov** [comment]
@mantonik 

Ugh, my fault. Set wrong type for item (`zabbix agent` instead of `zabbix trapper`).
You can manually change it to trapper from your configuration tab.

**Comment by mantonik** [comment]
ok thank you.

**Comment by netrusov** [comment]
Hope you liked ZabbixDBA!

Thanks,
Alex.

**Comment by mantonik** [comment]
Hi, 
I took latest release - it start without any problem. 
Thank you.
