### ISSUE TITLE
zabbix password

### ISSUE THREAD

**Issue by bigsow** [anetrusov/ZabbixDBA#31]
Where should I put the Zabbix password.
In your example configuration file There are host and port fields only.

**Comment by netrusov** [comment]
@bigsow 

Password for `ZABBIX` user must be set either in default section if this user has same password for every database (see https://github.com/anetrusov/ZabbixDBA/blob/master/conf/config.example.pl#L14), or overridden in certain database section if password is differs from default.

**Comment by bigsow** [comment]
I mean password for Zabbix application user, not to Oracle database user.

**Comment by netrusov** [comment]
@bigsow 

You don't need to specify Zabbix application user. It sends data to Zabbix trapper service, which works without any authentication: https://www.zabbix.com/documentation/3.2/manual/config/items/itemtypes/trapper

**Comment by bigsow** [comment]
So. Is it necessarty to configure the trapper service first?

**Comment by netrusov** [comment]
@bigsow 

Sure, there's template at [conf/templates](https://github.com/anetrusov/ZabbixDBA/tree/master/templates) directory that must be imported into Zabbix through web interface.
You can write your own queries by adding them to query file and create trapper items in Zabbix

**Comment by bigsow** [comment]
So why didn't you add more info about templates, trapper service to the manual, there is to many issues to gues?
Are the templates dedicated for Zabbix 3.0 and higher?
I have got Zabbix 2.8 and during import I get message "Unknown import version."

**Comment by netrusov** [comment]
@bigsow 

I'll update documentation, didn't have such questions before.

The issue with template is that it was exported from newer Zabbix version but it works fine with Zabbix >= 1.8. I'll update version later but it can be manually done just by editing third line of `Template_Oracle.xml`

Thanks.

**Comment by ffurlanetti** [comment]
Hi Anetrusov how are you?

I installed the service and following the instructions in README.md, apparently is everything OK with the service on the zabbix server, and I did not receive any error in .log nor in .err, as you can see below, but I did not receive any data on "Last Data"

Did I forgot to do something? Did I need to install and configure zabbix_sender on the zabbix_agentd.conf?

#cat /opt/zdba/log/zdba.log
[2017/03/21 17:49:06][INFO ] [27] starting ZabbixDBA (version 3.0.2)
[2017/03/21 17:49:06][INFO ] [53] starting thread for database 'MSFA_HOM'
