### ISSUE TITLE
ZabbixDBA failed to start

### ISSUE THREAD

**Issue by XavierFlo** [anetrusov/ZabbixDBA#42]
Hello,
I installed your plugin on my ZABBIX server (CentOS 7).
The installation is OK. But, the service failed to start.
I have nothing in logs.

Can you help me ? Thanks.

Xavier

**Comment by netrusov** [comment]
@XavierFlo 

Hello,

Please try to start service manually using `perl /path/to/zdba.pl /path/to/config.pl` and see the output.
But I'm sure that all logs should be in `/opt/zdba/logs` directory (if you put plugin to `/opt/zdba` of cource).

Thanks.

**Comment by XavierFlo** [comment]
Hello,

Thanks for your reply.
I works on my problem and I changed **ZabbixDBA.pl** to **zdba.pl** in your script  **/etc/init.d/zdba** and now I have :

Can't locate ZDBA.pm in @INC (@INC contains: lib /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /opt/zdba/zdba.pl line 14.
BEGIN failed--compilation aborted at /opt/zdba/zdba.pl line 14.


Sorry but I'm not a perl expert.

**Comment by netrusov** [comment]
@XavierFlo 

That's strange, there's an instruction at `zdba.pl:13` to use `lib` directory.
You can try to add path to zdba library directory manually by adding `PERL5LIB=/path/to/zdba/lib` to init script. I'll add it to the next release (need to test this before).

Can you please attach output of the following commands:
```
uname -a
perl --version
```

Thanks,

**Comment by XavierFlo** [comment]
Sorry no time for now. But I'll try your solution soon.

uname -a

`Linux test.local 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

 perl --version

```
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 34 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by netrusov** [comment]
@XavierFlo 

I didn't find any issues neither with `FindBin` nor with `lib` packages on this kernel version.

You can also try to apply the following patch to `zdba.pl`: https://github.com/anetrusov/ZabbixDBA/commit/db8841f78ed4b98d2baca3015f59d58f0af4be3a.patch
Save this file somewhere and execute `patch zdba.pl path/to.patch`

Waiting for an update from you.

**Comment by netrusov** [comment]
@XavierFlo 

Hi,

Any updates on this?

**Comment by XavierFlo** [comment]
Hi,
Sorry for my late answer.
I try your solution with no results.
```
 cat zdba.err
Can't locate ZDBA.pm in @INC (@INC contains: lib /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /opt/zdba/zdba.pl line 14.
BEGIN failed--compilation aborted at /opt/zdba/zdba.pl line 14.
```

I plane to replace centos by ubuntu so I come back  in one week after my migration.

Thanks to take time.

**Comment by tommy666666666** [comment]
Hi, Guys
   is there some one who alredy resolve this issue
BR//Tommy

**Comment by netrusov** [comment]
@tommy666666666 which version of perl do you use? and what error do you see in the error log?

I'm not sure why some people see this. I've just tried to debug this using the following script:
```perl
package main;

use strict;
use warnings;

use FindBin '$Bin';
use File::Spec;

print File::Spec->catfile($Bin, 'lib') . $/;

1;
```

it prints full path to the `lib` directory where the script is located, so everything seems to work just fine

**Comment by tommy666666666** [comment]
@netrusov 
Thanks for your reply quickly, i already resolved this problem. the reason is that can't automatic  install perl moduals successfully by cpan. so i have to install them  manually
