### ISSUE TITLE
Latest data empty

### ISSUE THREAD

**Issue by ttamirt** [anetrusov/ZabbixDBA#43]
I've configured ZabbixDBA as instructed for my Oracle DB, and imported Template_Oracle.xml. 'zdba' daemon is running and connecting to my db. In Latest data window there's nothing in 'Last check' and 'Last value' columns. What am I doing wrong?

**Comment by netrusov** [comment]
@ttamirt 

Hello,

Name of the database in `zdba` must match to Zabbix host name.
For example, you defined database `XXXDEV` in configuration file. Then you create `XXXDEV` host in Zabbix using `Template_Oracle.xml`.
When you start `zdba` it connects to the database using defined connection string, fetches data and tries to send it to Zabbix trapper in the following format:
```
{
  "host": "XXXDEV",
  "key": "key"
  "value": "value"
}
```
Zabbix makes a lookup by host name and assigns data to its keys.

**Comment by ttamirt** [comment]
Thanks, it works now. Previously I added Template Oracle to my existing db server, which I was monitoring other physical resources. Since I have 2 SID's, I cannot rename my current host. Instead I created two hosts with same names as my SID's. Thanks again.

**Comment by netrusov** [comment]
@ttamirt 

That's right. You must separate host monitoring and database monitoring.

Thanks, hope you liked it!

**Comment by elekgeek** [comment]
http://<IP>/zabbix/latest.php?filter_rst or http://<IP>/zabbix/latest.php?filter_rst=1 this will reset all filters for latest data page.

this worked OK for me
