### ISSUE TITLE
No data received for 5 minutes

### ISSUE THREAD

**Issue by ttamirt** [anetrusov/ZabbixDBA#45]
Hey there,
I'm monitoring 2 database instances. 1 is working fine, but the other one is showing this alert: "No data received for 5 minutes". What does it mean? I'm sure that both of my instances are working fine. What should I do? Do I have to restart the zabbix dba service?

**Comment by netrusov** [comment]
@ttamirt 

Hello,

It looks like `alive` check doesn't work properly.
Do you receive any data from this database? Does `alive` has data (`1` or `0`) on "Latest data" tab?

Thanks.

**Comment by ttamirt** [comment]
It was still throwing "PGA Almost fully committed.", "Archivelog generation is too fast" notifications. So I think it was receiving data. I've restarted "/sbin/service zdba" it's back to normal now. I didn't check the alive on Latest data. thanks anyway.
