### ISSUE TITLE
Не подключается к базе после рестарта базы

### ISSUE THREAD

**Issue by alostk** [anetrusov/ZabbixDBA#51]
День добрый.
Настроил все согласно инструкции.
Все работает, данные приходят.

Версия заббикса и агента - 3.2.4
cpanm DBD::Oracle
DBD::Oracle is up to date. (1.74)

Но после рестарта базы
> shutdown immediate
> startup
Информация о состоянии базы не обновляется.
В логе пишет 

ORA-03114: not connected to ORACLE (DBD ERROR: OCIStmtExecute/Describe)
[2017/03/16 10:55:59][INFO ] [ZDBA::monitor:143] completed fetching data on 'xxx' (elapsed 0.018305)

Спасает только перезагрузка сервиса zdba, после этого получается подключиться к базе.

В чем может быть причина?

**Comment by netrusov** [comment]
@alostk 

Добрый день,

Я в данный момент решаю эту проблему. Подобное может произойти и при удалении конфигурации базы.

Надо пофиксить работу форков.

**Comment by paidem** [comment]
Hi, I have same problem.

As a temporary solution I changed

$self->connect unless $self->dbh;

to

$self->connect unless ($self->dbh && not $self->dbh->ping);

in /opt/zdba/lib/ZDBA/DBIx.pm  file

So that it pings db on every query and reconnects if connection is lost.

**Comment by netrusov** [comment]
@alostk @paidem 

fix is in `master` branch, you can checkout to the newest version.
feel free to open issues or communicate via e-mail!
