### ISSUE TITLE
ZabbixDBA don't receive any data

### ISSUE THREAD

**Issue by ffurlanetti** [anetrusov/ZabbixDBA#55]
I installed and configured the zbda on CentOS 7 server.
I imported the Template. I did all procedures following the instructions of instalation, but I don't received any data on zabbix server.

I need to use zabbix_sender?

**Comment by netrusov** [comment]
@ffurlanetti 

hello,

did you see these issues: #43, #44? names must be the same in configuration file and in zabbix

**Comment by netrusov** [comment]
as I see in your [comment](https://github.com/anetrusov/ZabbixDBA/issues/31#issuecomment-288253074) you have database named `MSFA_HOM`. do you have host with the same name in zabbix?

**Comment by netrusov** [comment]
you can find a screencast on how to install and configure ZabbixDBA in [Wiki](https://github.com/anetrusov/ZabbixDBA/wiki#screencasts)

**Comment by ffurlanetti** [comment]
Hi Anetrusov, thanks to answer my question.

Great! I did what you say, and now I'm receive some data, like 'DB version', 'Alive' and etc.

But now I think that the problem is permission at database,

Error message:

[2017/03/22 12:33:52][INFO ] [ZDBA::monitor:42] starting monitoring of 'SSCD2306'
[2017/03/22 12:33:52][INFO ] [ZDBA::DBIx::connect:47] **connected** to 'DBI:Oracle:host=sscd2306.j01.jequiti.com.br;port=1521;sid=MSFA_HOM'
[2017/03/22 12:33:52][ERROR] [ZDBA::DBIx::_fetch:95] failed to execute query on 'DBI:Oracle:host=sscd2306.j01.jequiti.com.br;port=1521;sid=MSFA_HOM':
ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 38 in '
        select count(*)
        from <*>gv$log_history
        where first_time >= (sysdate - 1 / 24)
    ')**

**Comment by netrusov** [comment]
@ffurlanetti 

yes, you must grant permissions to zabbix to read system tables. you can grant `SELECT_CATALOG_ROLE` if it's possible.

**Comment by ffurlanetti** [comment]
Thanks one more time Anetrusov e congratulation for the Zabbix DBA, nice job and nice support!

**Comment by netrusov** [comment]
@ffurlanetti thanks for the kind words!
