### ISSUE TITLE
is it possible monitor ASM?

### ISSUE THREAD

**Issue by netrusov** [anetrusov/ZabbixDBA#58]
per request by @ffurlanetti on share.zabbix.com

> is it possible get ASM spaces like Tablespaces?

yes, you can monitor ASM if you have query. please read [Discovery rules](https://github.com/anetrusov/ZabbixDBA/wiki/Discovery-rules) page in Wiki.
I can help you to configure this.

waiting for your answer.

**Comment by ffurlanetti** [comment]
Hi!
So I'll request to our DBA to create the query.

Thanks a lot again!
