### ISSUE TITLE
How to integrate ZabbixDBA in Zabbix Portal

### ISSUE THREAD

**Issue by petonwu** [anetrusov/ZabbixDBA#59]
Hi Guru,

I have installed and configured ZabbixDBA on my Oracle Database server successfully, and see the log with the message "[2017/05/04 18:39:26][INFO ] [ZDBA::monitor:143] completed fetching data on 'ORCL' (elapsed 0.151285)". And I have tried to integrate the zabbixDBA to zabbix portal with importing the ZabbixDBA template and creating a new host with ip(127.0.0.1) ,port(10050) and the Oracle template which have been imported previously. 
However, I didn't see any data collected by ZabbixDBA, could you please show me how to integrate zabbixDBA correctly? or where can I check whether the data is collected successfully?

Look forward of your kindly help!

Thanks,
Peton

**Comment by netrusov** [comment]
@petonwu 

hi,

did you see my [screencast](https://youtu.be/R0O2rmI_OVs) on how to configure ZabbixDBA?
as I see you've added `ORCL` entry to config, so you have to create host in Zabbix with the same name.
also you can give any name to your database in configuration file, just be sure to specify correct name in database connection string.

P.S.: there's a way to debug zdba just by changing `INFO` to `DEBUG` in `config/log4perl.conf` file:

```
# change this line
log4perl.rootLogger = INFO, LOGFILE

# to this
log4perl.rootLogger = DEBUG, LOGFILE
```

thanks.

**Comment by petonwu** [comment]
It works,thanks Anetrusov for your kindly help! Currently, do you have any solution of monitoring Oracle RAC?

Thanks,
Peton

**Comment by netrusov** [comment]
@petonwu 

no, what kind of monitoring do you mean?

**Comment by petonwu** [comment]
I  mean Oracle RAC(Real Application Cluster) monitoring.Currently, I just see the single database monitoring.

Thanks,
Peton

**Comment by netrusov** [comment]
@petonwu 

I know what RAC means, but I don't know what kind of metrics ZabbixDBA should gather.
can you please give an example?

**Comment by petonwu** [comment]
@anetrusov I will give the monitoring metrics for RAC later! one more question, zabbixDBA uses agent(127.0.0.1:10050) to report its monitored data? because when zabbixDBA is integrated into zabbix portal, we need to use the agent IP address and port number.

**Comment by netrusov** [comment]
@petonwu 

no, it doesn't use Zabbix Agent at all. it uses [Zabbix Trapper](https://www.zabbix.com/documentation/3.0/manual/config/items/itemtypes/trapper), `127.0.0.1` is just a stub because you can't remove all interfaces. actually you can use IP of your database server and add custom OS metrics (for example, when you want to monitor Oracle alert log)

**Comment by petonwu** [comment]
Thanks Anetrusov!!! can zabbixDBA collected Oracle data be used in Grafana?

**Comment by netrusov** [comment]
@petonwu 

I didn't work with Grafana but if it takes data from Zabbix it should be possible.

I'm closing this ticket.

thanks.
