### ISSUE TITLE
installation lacs not on renaming config.example.pl

### ISSUE THREAD

**Issue by louigi600** [anetrusov/ZabbixDBA#60]
I follower notes on README.md but could not get zdba to start.
Looking at the logs I noticed a referenc to a file that did not exist but there was an equifalent smple file.
I renamed it without sample and zdba started.

**Comment by netrusov** [comment]
@louigi600 

hi,

documentation in `README.md` is old and everything is now stored in [Wiki](https://github.com/anetrusov/ZabbixDBA/wiki), branch `develop` already has updated readme.
also, there's a good screencast on how to configure ZabbixDBA (see link in Wiki)

thanks.

**Comment by louigi600** [comment]
I missed the wiki ... I'll have a look thee because now I've a few perplexities on how to configure the databases to monitor. 
Thanx 
David
