### ISSUE TITLE
does zabbix 3.0 can used?

### ISSUE THREAD

**Issue by powersam** [anetrusov/ZabbixDBA#67]
does zabbix 3.0 can used? 
my zabbix server is 3.0 when i import template i always get error
已创建: 监控项 "Primary archived log sequence" 于 "Template Oracle Standby".
Cannot find item "blocking_sessions" on "Template Oracle" used in trigger "Blocking sessions".

thank you very much

**Comment by powersam** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>3.0</version>
    <date>2017-05-19T07:49:58Z</date>
    <groups>


thank youu i got it

**Comment by netrusov** [comment]
@powersam 

hi, problem solved?
