### ISSUE TITLE
Not working with hosts via proxy

### ISSUE THREAD

**Issue by waszpaw** [anetrusov/ZabbixDBA#68]
The same host working with direct communication works perfectly. When switched to work through proxy it does not recognize the data sent by perl scripts (they seem to be working fine, though) - no new data is showing up in the "history" table.

**Comment by netrusov** [comment]
hello Pawel,

seems like an issue with Zabbix. I've searched and found that people encounter the same problem when using Zabbix Trapper over Proxy, some of them say that it takes some time to transmit data from proxy to server.
honestly, I've never worked with Zabbix Proxy and don't know how to help right now. can you try to send data using zabbix_sender and see if it's received by server?

thanks.

**Comment by waszpaw** [comment]
Hopefuly, I have my answer. After some experimetns with zabbix_sender (thanks Alex) I realized that it's a bit misleading in the short help. Manual explains - if the host is monitored through a proxy, use the proxy address instead of the server. I changed it in the ZabbixDBA configuration and seems to be working now.

**Comment by netrusov** [comment]
that's great, thanks for the explanation!
will add this information to Wiki
