### ISSUE TITLE
Multiple proxies

### ISSUE THREAD

**Issue by waszpaw** [anetrusov/ZabbixDBA#69]
Hi there, continuation of the thread about proxies. To work with a proxy it was necessary to replace zabbix server address with proxy IP (in config.pl, section "zabbix"). It comes from the zabbix trapper behavior, OK.
But, it kinda blocks me if I use more than one proxy (which is probably quite common). Is there a way to have multiple addresses under one config for each proxy?

**Comment by netrusov** [comment]
@waszpaw 

hi,

there was a way to add multiple Zabbix servers to configuration, but I removed it because didn't know if it could be helpful. will add in the next release.
unfortunately, I didn't have much time to check your solution with proxies and to write article on this, but will do later.
also, your issue wasn't removed, it's just right there - #68 (it's closed)

thanks.

**Comment by waszpaw** [comment]
Yes, I just realized and edited my comment.

**Comment by waszpaw** [comment]
@Alex, you wrote about the next release. May I kindly ask what are your plans in this regard? When do you expect it? Reasoning - if it's soon, I'm happy to be your loyal customer;-) If not, I need to look around for another solution (which would be pity).

**Comment by netrusov** [comment]
@waszpaw 

hi,

I'll fix this in the next few days (maybe today will push to develop), just need to be sure that it won't break configuration of other users.

thanks.

**Comment by netrusov** [comment]
@waszpaw 

I've created PR #70 
you can checkout to branch `feature/multiple-zabbix-servers` and check if everything is working fine.
to enable multiple Zabbix targets you can set configuration entry like this:

```
zabbix => [
  { host => 'zabbix-server' },
  { host => 'zabbix-proxy-01' },
  { host => 'zabbix-proxy-02' },
]
```

**Comment by waszpaw** [comment]
Thanks! I just saw your pull request, I'll be testing on Friday. Just a question - apart from the multiple servers definition - how should I refer to different instances? E.g. - all of them should have the same Oracle user and password? In the "list" parameter should I mix aliases leading to instances via different proxies?

**Comment by netrusov** [comment]
@waszpaw 

hmm, not sure if I understood your question correctly. can you please give more detailed example?

**Comment by waszpaw** [comment]
Sure. Le't say, currently my config looks like this:
`{zabbix => {
host    => '10.113.2.125',
port    => 10051,
timeout => 30,
},
  daemon => {
    sleep => 240,
    split_logs => 1
  },
  db => {
    default => {
      user       => 'zabbix',
      pass       => 'zabbix',
      query_list => 'query.props.pl',
      sleep      => 120,
      retry_step => 1,
    },
    list   => [qw|BTOP_PRE_BS BTOP_PRE_IPB BTOP_PRE_CRM BTOP_PRE_SC BTOP_PRE_MDSPIM BTOP_PRE2_BS BTOP_PRE2_CRM BTOP_PRE2_SC BTOP_PRE2_MDSPIM BTOP_PROD_BS BTOP_PROD_IPB BTOP_PROD_CRM BTOP_
PROD_SC BTOP_PROD_MDSPIM|],
    BTOP_PRE_BS => {
      dsn       => 'DBI:Oracle:host=10.113.2.221;port=1530;sid=BS'
    },
    BTOP_PRE_IPB => {
      dsn       => 'DBI:Oracle:host=10.113.2.222;port=1531;sid=IPB'
    },
`

**Comment by waszpaw** [comment]
;-) Let's wait until Friday, it will be easier to check what I think is OK and bother you only if I cannot find a solution.

**Comment by netrusov** [comment]
ok. also, don't forget that you can run multiple instances of application by creating different configuration files:
```
perl zdba.pl config-01.pl
perl zdba.pl config-02.pl
...
perl zdba.pl config-N.pl
```

**Comment by waszpaw** [comment]
I connected two proxies and one bare zabbix server without significant problems. So far everything is working fine. I'll continue observing and let you know if anything happens. Anyway - THANKS.

**Comment by netrusov** [comment]
thanks for feedback 👍
