### ISSUE TITLE
Zabbix не получает некоторые данные из-за ограничений на float.

### ISSUE THREAD

**Issue by allanian** [anetrusov/ZabbixDBA#74]
Здравствуйте, подскажите пожалуйста, настроил ZabbixDBA. Работает почти все, хотелось бы разобраться с вот такими сообщениями в логах заббикса. Насколько я помню в заббиксе ограничение на количество знаков после точки - 4. Можете ограничить? на данные параметры
dbhitratio, pinhitratio_sqlarea,pinhitratio_table_proc,pinhitratio_sqlarea. Спасибо)
"TEST:dbhitratio" changed: Received value [97,20849231] is not suitable for value type [Numeric (float)]
"TEST:hitratio_sqlarea" changed: Received value [97,83847580] is not suitable for value type [Numeric (float)]
"TEST:pinhitratio_sqlarea" changed: Received value [99,9521649171] is not suitable for value type [Numeric (float)]
"TEST:pinhitratio_table_proc" changed: Received value [99,671535825] is not suitable for value type [Numeric (float)]

**Comment by netrusov** [comment]
добрый день,

проблема не в количестве знаков, а в переменной среды NLS_LANG на сервере, где запущен  ZabbixDBA. в Zabbix тип данных Float отделяется не запятой, а точкой.
в wiki как раз есть решение для этой проблемы: https://github.com/anetrusov/ZabbixDBA/wiki/Frequently-Asked-Questions

**Comment by allanian** [comment]
Добрый день, спасибо за уточнение, проблема в том что базы стоят в кодировке Russian_CIS.CL8MSWIN1251 и изменить её нет возможности. Если на сервере заббикса выставляю AMERICAN_AMERICA.AL32UTF8 - вылетает ошибка с некорректным NLS_LANG.
Помогло - export NLS_LANG=american_america.CL8MSWIN1251. Спасибо за подсказку.

**Comment by netrusov** [comment]
отлично, отображу это в FAQ
