### ISSUE TITLE
ORA-24373: invalid length specified for statement (DBD ERROR: OCIStmtPrepare)

### ISSUE THREAD

**Issue by avs262** [anetrusov/ZabbixDBA#76]
I've configured a custom query file but I'm receiving the following error when zdba attempts to run the query. Any advice?

Contents of query file:
`{
  list => [
    'iowaits_cpu'
  ],
  archivelog_switch => {
    query => q{
      WITH system_event AS
  (SELECT CASE
            WHEN wait_class IN ('User I/O', 'System I/O')
            THEN event ELSE wait_class
           END  wait_type, e.*
      FROM v$system_event e)
SELECT wait_type, SUM(total_waits) / 1000 waits_1000,
     ROUND(SUM(time_waited_micro))
           time_waited_hours
FROM (SELECT wait_type, event, total_waits, time_waited_micro
    FROM system_event e
    UNION
    SELECT 'CPU', stat_name, NULL, VALUE
    FROM v$sys_time_model
    WHERE stat_name IN ('background cpu time', 'DB CPU')) l
WHERE wait_type = 'CPU'
GROUP BY wait_type
    },
  },
}`

error:
[2017/10/04 10:38:16][ERROR] [ZDBA::DBIx::_fetch:95] failed to execute query on 'DBI:Oracle:host=x.x.x.x;port=1521;sid=xxx':
ORA-24373: invalid length specified for statement (DBD ERROR: OCIStmtPrepare)

**Comment by netrusov** [comment]
hi @avs262 

looks like you've made a mistake in `list` node. you've specified `iowaits_cpu`, but then used `archivelog_switch` key. zdba didn't find `iowaits_cpu` in query list and tried to execute empty query. fix query names and try again.

**Comment by netrusov** [comment]
please reopen this request if provided solution didn't work.

thanks.
