### ISSUE TITLE
ORA-01000: maximum open cursors exceeded (DBD ERROR: OCIStmtExecute)

### ISSUE THREAD

**Issue by hawkinspeter** [anetrusov/ZabbixDBA#77]
After installing ZabbixDBA and running it, I get ORA-01000 in the logs. The database has a high value of open_cursors, so it looks like a bug with not closing cursors correctly in ZabbixDBA.

Here's a typical error from the log:

[2017/10/09 11:23:30][ERROR] [ZDBA::DBIx::_fetch:95] failed to execute query on 'DBI:Oracle:host=uk01pora001;port=1521;sid=casprod1':
ORA-01000: maximum open cursors exceeded (DBD ERROR: OCIStmtExecute)

Anyone got any ideas?

**Comment by netrusov** [comment]
hi @hawkinspeter 

thanks for finding this bug. didn't have such problems before probably because parameter `open_cursors` was set to higher values, but now I see that there're 41 open cursors for single session in my database.

I'll investigate the issue and write back later.

thanks.

**Comment by hawkinspeter** [comment]
I'm quite puzzled by this as I increased our open_cursors parameter from 1500 up to 15000 to see what was happening and it still gave ORA-01000. I queried the v$open_cursor view and the zabbix user only had around 50 cursors open (we've got over a 1000 cursors open for one of our Java applications that's a bit buggy).

**Comment by netrusov** [comment]
looks like everything's ok in Perl's DBI module.

I'm using `selectrow_arrayref` method to fetch rows, which is using `_do_selectrow` under the hood (see lines 1650 and 1636 of [DBI.pm](https://metacpan.org/source/TIMB/DBI-1.637/DBI.pm)). it opens and closes cursor for each statement, so there're only cursors in `SESSION CURSOR CACHED` state left, not `OPEN`.

yes, there's a problem that I'm creating cursors for each statement (and I'll fix it later), but it shouldn't cause any issues.

can you please send me version of your database and command which you're executing to change number of open cursors?

thanks.

**Comment by hawkinspeter** [comment]
We're running Oracle RAC 11gR2 11.2.0.4.0 Standard Edition. It's got 2 nodes which I've set up in config.pl.

To change the number of open_cursors, I'm using:
alter system set open_cursors=15000 sid='*' scope=both;

I've also tried setting "alter session set session_cached_cursors=0" as a workaround when the zabbix user logs on, but it doesn't make any difference.

The Zabbix server is running Ubuntu 16.04.

**Comment by netrusov** [comment]
hi @hawkinspeter 

do you still encounter the same problem? I didn't have time yet to fix this.

**Comment by hawkinspeter** [comment]
Hi,
I ended up using DBforBIX instead, so don't worry about this bug (unless someone else is getting it too).

**Comment by acidjepz** [comment]
Hello, i have the same problem on oracle 11gR2 11.2.0.4.0. If you have time to fix i'd be really grateful.
