### ISSUE TITLE
Unable to run perl zdba.pl 

### ISSUE THREAD

**Issue by choudharypankaj** [anetrusov/ZabbixDBA#80]
I'm getting the following error while executing : perl zdba.pl conf/config.pl

Thread 1 terminated abnormally: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /opt/database/ZabbixDBA-master/lib/ZDBA.pm line 122

**Comment by mantonik** [comment]
I also get into this problem. 
I was trying to setup a user zdba with perl and new version of zdba,

Any sugestion what could cause a problem? it is related to config file?

**Comment by choudharypankaj** [comment]
I resolved the error by upgrading the PHP version. I'm currently running on PHP 5.6.32.

**Comment by mantonik** [comment]
Thank you for info.
I did update of PHP from 5.3.3 to 5.6.32 but this doesn't resolve the problem. 

Startup script and configuration files are Perl scripts not php.

perl version is version 
This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

**Comment by netrusov** [comment]
@choudharypankaj @mantonik 

can you please enable debug and see what it's trying to send? debug message should look like this: https://github.com/anetrusov/ZabbixDBA/blob/master/lib/ZDBA/DBIx.pm#L98

see how to enable debug: https://github.com/anetrusov/ZabbixDBA/wiki/Frequently-Asked-Questions

thanks.

**Comment by mantonik** [comment]
Here is couple minutes of log with error.

[XMSPRODDATA.log](https://github.com/anetrusov/ZabbixDBA/files/1575694/XMSPRODDATA.log)
[zdba.log](https://github.com/anetrusov/ZabbixDBA/files/1575695/zdba.log)
[zdba.err.log](https://github.com/anetrusov/ZabbixDBA/files/1575696/zdba.err.log)

Thank  you

**Comment by netrusov** [comment]
@mantonik 

I've created new branch with fix for this: https://github.com/anetrusov/ZabbixDBA/pull/82. can you please test it?

**Comment by mantonik** [comment]
Thank you

**Comment by mantonik** [comment]
Hi

The static query is executed and data is collected, but discovery rules look like is executed and data is retrieved from DB but it is not sent to zabbix server (before this was not sent)

from below config I get mas_exported_date values but not below discovery rules. 
Oracle tablespace discovery - no data from that one.

Config files I copy those which I was using the previous version.

{
  list => [
        'mas_exported_date',
       ],
  mas_exported_date => {
        query => q{
        select count(*) count from p_trx where term_no in (select terminal_no from g_terminals where terminal_model = 17) and trx_date > sysdate - 3/24
        },
  },
  #Discovery rules
    discovery => {
      rule => {
        vds => {
          query => q{select terminal_no VDS_ID from g_terminals where  terminal_model = 15 },
          keys => ['VDS_ID'],
        },
      },
      item => {
        VDS_LOWDATA => {
          query => q{
            select VDS_ID, listagg(LOW_VAL_COUNT,'; ' )   within group ( order by vds_id) LOW_VAL_COUNT  from XMS.SUP_GATE_VALIDATION_COUNT_MW group by vds_id order by vds_id asc
          },
          keys => { VDS_ID => 'LOW_VAL_COUNT' }
        },

      },
    },
}


[zdba.err.log](https://github.com/anetrusov/ZabbixDBA/files/1576224/zdba.err.log)
[zdba.log](https://github.com/anetrusov/ZabbixDBA/files/1576225/zdba.log)
[XMSPRODDATA.log](https://github.com/anetrusov/ZabbixDBA/files/1576226/XMSPRODDATA.log)

**Comment by mantonik** [comment]
Hi, any update on this?

**Comment by choudharypankaj** [comment]
I'm not sure, but I think I resolved the issue by installtion perl-5.20.2.

Can you check if "cpanm" is installed on your server.  Also, can you check the output of the command:
perl -E 'BEGIN{unshift @INC, ".";} use forks'

**Comment by netrusov** [comment]
@mantonik hi, sorry for silence, but I didn't figure it out yet. I've checked multiple times on several installations and didn't have any errors.

@choudharypankaj thanks, that must be right answer. maybe something changed in newer versions of perl and plugin doesn't work properly now.

@mantonik can you please install perl <= 5.20.0 and test again?

**Comment by netrusov** [comment]
@mantonik also, if you use perlbrew (as recommended), installing another version of perl shoul be easy.

**Comment by mantonik** [comment]
Thank you.
I will try and let you know. I am using perlbrew.

**Comment by mantonik** [comment]
I moved to perl 5.20.0  but I still see an error 

[2018/01/10 21:24:52][DEBUG] [ZDBA::Sender::send_chunk:110] sending chunk to Zabbix:
{"data":[{"key":"alive","host":"XMSPRODDATA","value":1},{"value":"4692","host":"XMSPRODDATA","key":"mas_exported_date"}],"request":"sender data"}
[2018/01/10 21:24:52][DEBUG] [ZDBA::Sender::send_chunk:117] chunk has been sent to Zabbix
[2018/01/10 21:24:52][DEBUG] [ZDBA::monitor:162] thread for 'XMSPRODDATA' is going to sleep for 602 sec.

==> XMSPROD.log <==
          {
            'CLASS' => 'Idle'
          },
          {
            'CLASS' => 'Network'
          },
          {
            'CLASS' => 'Commit'
          }
        ];

==> XMSQA.log <==
          {
            'TS' => 'TSP_QUICKTICKET'
          },
          {
            'TS' => 'TSP_SUPPORT_TMP'
          },
          {
            'TS' => 'TSP_BANK'
          }
        ];

==> zdba.err <==
Thread 1 terminated abnormally: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /home/zdba/ZabbixDBA/lib/ZDBA.pm line 122.
Thread 4 terminated abnormally: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /home/zdba/ZabbixDBA/lib/ZDBA.pm line 122.
Thread 2 terminated abnormally: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /home/zdba/ZabbixDBA/lib/ZDBA.pm line 122.

[zdba@databackup log]$ ps -ef|grep zdba
root     29672 32307  0 21:19 pts/1    00:00:00 sudo su - zdba
root     29673 29672  0 21:19 pts/1    00:00:00 su - zdba
zdba     29674 29673  0 21:19 pts/1    00:00:00 -bash
zdba     30868     1  0 21:24 ?        00:00:00 /home/zdba/perl5/perlbrew/perls/perl-5.20.0/bin/perl /home/zdba/ZabbixDBA/ZabbixDBA.pl /home/zdba/ZabbixDBA/conf/config.pl
zdba     30870 30868  0 21:24 ?        00:00:00 /home/zdba/perl5/perlbrew/perls/perl-5.20.0/bin/perl /home/zdba/ZabbixDBA/ZabbixDBA.pl /home/zdba/ZabbixDBA/conf/config.pl
zdba     30888 30868  0 21:24 ?        00:00:00 /home/zdba/perl5/perlbrew/perls/perl-5.20.0/bin/perl /home/zdba/ZabbixDBA/ZabbixDBA.pl /home/zdba/ZabbixDBA/conf/config.pl
zdba     31154 30868  1 21:26 ?        00:00:00 /home/zdba/perl5/perlbrew/perls/perl-5.20.0/bin/perl /home/zdba/ZabbixDBA/ZabbixDBA.pl /home/zdba/ZabbixDBA/conf/config.pl
zdba     31163 29674  3 21:26 pts/1    00:00:00 ps -ef
zdba     31164 29674  0 21:26 pts/1    00:00:00 grep zdba

**Comment by mantonik** [comment]
Hi 
I used Perl 5.10 from Linux distribution - it is working. 
5.10 is the end of life, what can be done that this will work with the latest version of Perl?

**Comment by netrusov** [comment]
@mantonik 

I'll see what can be done, but now you can try to do what's suggested in error message - add `use allow_nonref;` somewhere in the header of `zdba.pl`
