### ISSUE TITLE
failed to compile extra.query.props.pl

### ISSUE THREAD

**Issue by pavkamlc** [anetrusov/ZabbixDBA#86]
I can't compile:

[root@zabbix ZabbixDBA]# perl zdba.pl conf/config.pl
Thread 1 terminated abnormally: failed to compile file '/opt/ZabbixDBA/conf/extra.query.props.pl':  at /opt/ZabbixDBA/lib/ZDBA/Config.pm line 37 thread 1.
        ZDBA::Config::compile('ZDBA::Config=HASH(0x1a18cf8)', '/opt/ZabbixDBA/conf/extra.query.props.pl') called at /opt/ZabbixDBA/lib/ZDBA.pm line 69 thread 1
        ZDBA::monitor('ZDBA=HASH(0x1883248)', 'ARBES') called at zdba.pl line 58 thread 1
        main::__ANON__() called at /usr/local/lib64/perl5/forks.pm line 799 thread 1
        eval {...} called at /usr/local/lib64/perl5/forks.pm line 799 thread 1
        threads::new('threads', 'CODE(0x104d180)') called at zdba.pl line 59 thread 1

**Comment by netrusov** [comment]
hi @pavkamlc,

sorry for delay.
there's syntax error somewhere in config file, but I hope that you've already figured it out.

thanks.
