### ISSUE TITLE
Sender with encryption?

### ISSUE THREAD

**Issue by linuxfool76** [anetrusov/ZabbixDBA#87]
Would it be possible to rework the Sender code to connect with encryption?

Thanks!
Neil

**Comment by netrusov** [comment]
hi Neil,

I didn't check Zabbix documentation for a long time and don't know if they support secure connections for trapper (but I'm sure not).
if you've configured ZDBA in DMZ I suggest you to create Zabbix Proxy in that segment of network and use it to send data to your main Zabbix server using its internal secure connection.

hope that helps,
thanks.
