### ISSUE TITLE
coercion for "config" failed: isa check for "file" failed: not a valid file at /opt/zdba/lib/ZDBA/Config.pm line 16

### ISSUE THREAD

**Issue by possebon** [anetrusov/ZabbixDBA#90]
Hi,

I'm trying to use ZabbixDBA. I installed on Oracle Linux where I have Oracle Server running.

I did the perl -c conf/config.pl and it says OK.

When I try to run:

`perl /opt/zdba/zdba.pl /opt/zdba/conf/config.pl`

I have this error message:

`coercion for "config" failed: isa check for "file" failed: not a valid file at /opt/zdba/lib/ZDBA/Config.pm line 16
        ZDBA::Config::_ANON_(undef) called at (eval 108) line 98
        eval {...} called at (eval 108) line 97
        ZDBA::Config::new('ZDBA::Config', 'HASH(0x1594c98)') called at /opt/zdba/lib/ZDBA.pm line 26
        ZDBA::_ANON_('HASH(0x1594c98)') called at (eval 107) line 79
        eval {...} called at (eval 107) line 78
        ZDBA::new('ZDBA', 'config', 'HASH(0x1594c98)') called at /opt/zdba/zdba.pl line 25
`

I looked at log folder and try to find any additional error message, without success.

**Comment by netrusov** [comment]
hi @possebon 

which version of perl do you use?
