### ISSUE TITLE
Issue during "perl zdba.pl conf/config.pl

### ISSUE THREAD

**Issue by secad04** [anetrusov/ZabbixDBA#93]
Hello,

I am getting this below error, when I execute perl zdba.pl conf/config.pl

coercion for "config" failed: isa check for "file" failed: not a valid file at /home/deadmin/zdba/lib/ZDBA/Config.pm line 16.
        ZDBA::Config::__ANON__("/home/deadmin/zdba/conf/config.pl") called at (eval 89) line 98
        eval {...} called at (eval 89) line 97
        ZDBA::Config::new("ZDBA::Config", HASH(0x562cd1f41e88)) called at /home/deadmin/zdba/lib/ZDBA.pm line 26
        ZDBA::__ANON__(HASH(0x562cd1f41e88)) called at (eval 88) line 81
        eval {...} called at (eval 88) line 78
        ZDBA::new("ZDBA", "config", HASH(0x562cd1f41e88)) called at zdba.pl line 25

I have followed all steps without any errors.

Would appreciate if you can help, as our DB is 11G and no other zabbix template works.

Thanks,
Ahmed

**Comment by netrusov** [comment]
hi @secad04 

looks like you have a typo in your config somewhere. you can check it by running `perl -c conf/config.pl` - this command will compile the file and tell if it has any syntax errors
